CREATE TABLE IF NOT EXISTS t_maestros_log (
	"id_log" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"accion" varchar(20) NOT NULL,
	"usuario" varchar(50) NOT NULL,
	"fecha" timestamp NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION fn_log_t_maestros()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO t_maestros_log ("accion", "usuario")
	VALUES (TG_OP, current_user);
	RETURN NULL;
END;
$$;

CREATE TRIGGER trg_log_t_maestros
AFTER INSERT OR UPDATE OR DELETE ON t_maestros
FOR EACH ROW EXECUTE FUNCTION fn_log_t_maestros();


CREATE TABLE IF NOT EXISTS t_asistencias_log (
	"id_log" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	"accion" varchar(20) NOT NULL,
	"usuario" varchar(50) NOT NULL,
	"fecha" timestamp NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION fn_log_t_asistencias()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	INSERT INTO t_asistencias_log ("accion", "usuario")
	VALUES (TG_OP, current_user);
	RETURN NULL;
END;
$$;

CREATE TRIGGER trg_log_t_asistencias
AFTER INSERT OR UPDATE OR DELETE ON t_asistencias
FOR EACH ROW EXECUTE FUNCTION fn_log_t_asistencias();
